name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Integration Test
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: run
          args: go run ci/dagger/main.go
          version: "latest"